### ISSUE TITLE
关于-Zi-Zi's Journey

### ISSUE THREAD

**Issue by GZ-Metal-Cell** [GZ-Metal-Cell/GZ-Metal-Cell.github.io#6]
https://gz-metal-cell.github.io/about/ 

 ZZ的博客

**Comment by promefire** [comment]
关哥牛逼

**Comment by promefire** [comment]
关哥新年快乐！！！！祝关哥新的一年快快乐乐！！！！！！！！！！！

**Comment by promefire** [comment]
https://rss.okggrss.top/link/PavEtMs4Q7Ksp9QN?mu=2

**Comment by GZ-Metal-Cell** [comment]
> @promefire
> 关哥新年快乐！！！！祝关哥新的一年快快乐乐！！！！！！！！！！！

😍😍😍promefire new bee! 早日发 Electronics!

**Comment by promefire** [comment]
每天起床第一句，先给关哥问个好！

**Comment by promefire** [comment]
太强了金属细胞 310个人找到了这里！！！！

**Comment by promefire** [comment]
去后台把我调到311好吗 /(ㄒoㄒ)/~~
